const DATA = [
    {
        id:1,
        title:"vivo Y15",
        image:"/images/vivo/vivo5.png" ,
        price:6999,
        stars:4.2,
        category:"Vivo",
        screen:"6.35",
        camera:"13MP",
        ram:"4GB",
        storage:"64GB",
        battery:"5000mAH",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:2,
        title:"vivo Y16",
        image:"/images/vivo/vivo2.png" ,
        price:79000,
        stars:4.2,
        category:"Vivo",
        screen:"6.51",
        camera:"15MP",
        ram:"4GB",
        storage:"64GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:3,
        title:"vivo Y21",
        image:"/images/vivo/vivo4.png" ,
        price:12380,
        stars:4.2,
        category:"Vivo",
        screen:"6.50",
        camera:"15MP Rear + 8MP Front",
        ram:"4GB",
        storage:"128GB",
        battery:"5000mAH",
        os:"Android 11",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:4,
        title:"vivo Y22",
        image:"/images/vivo/vivo3.png" ,
        price:13999,
        stars:4.2,
        category:"Vivo",
        screen:"6.55",
        camera:"50MP Rear + 8MP Front",
        ram:"4GB, 6GB",
        storage:"64GB, 128GB",
        battery:"5000mAH",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:5,
        title:"vivo V23 pro",
        image:"/images/vivo/vivo6.png" ,
        price:38990,
        stars:4.2,
        category:"Vivo",
        screen:"6.56",
        frontcamera:"50MP + 2MP",
        rearcamera:"108MP + 8MP + 2MP",
        ram:"8GB, 12GB",
        storage:"128GB, 256GB",
        battery:"4300mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:6,
        title:"vivo V25 pro",
        image:"/images/vivo/vivo7.png" ,
        price:79000,
        stars:4.2,
        category:"Vivo",
        screen:"6.56",
        frontcamera:"32MP",
        rearcamera:"64MP + 8MP + 2MP",
        ram:"8GB, 12GB",
        storage:"128GB, 256GB",
        battery:"4830mAH",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:7,
        title:"vivo Y33T",
        image:"/images/vivo/vivo8.png" ,
        price:16990,
        stars:4.2,
        category:"Vivo",
        screen:"6.58",
        frontcamera:"16MP",
        rearcamera:"50MP + 2MP + 2MP",
        ram:"8GB",
        storage:"128GB",
        battery:"5000mAH",
        os:"Android 11",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:8,
        title:"vivo Y35",
        image:"/images/vivo/vivo9.png" ,
        price:79000,
        stars:4.2,
        category:"Vivo",
        screen:"6.51",
        frontcamera:"5MP",
        rearcamera:"13MP + 2MP",
        ram:"4GB, 8GB",
        storage:"128GB",
        battery:"5000mAH",
        os:"Android 13",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:9,
        title:"vivo X60",
        image:"/images/vivo/vivo10.png" ,
        price:35090,
        stars:4.2,
        category:"Vivo",
        screen:"6.56",
        frontcamera:"32MP",
        rearcamera:"48MP + 13MP + 13MP",
        ram:"4GB",
        storage:"64GB",
        battery:"4300mAH",
        os:"Android 11",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:10,
        title:"vivo Y75",
        image:"/images/vivo/vivo11.png" ,
        price:19990,
        stars:4.2,
        category:"Vivo",
        screen:"6.44",
        frontcamera:"44MP",
        rearcamera:"50MP + 8MP + 2MP",
        ram:"8GB",
        storage:"128GB",
        battery:"4050mAH",
        os:"Android 11",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:11,
        title:"vivo X80",
        image:"/images/vivo/vivo12.png" ,
        price:79000,
        stars:4.2,
        category:"Vivo",
        screen:"6.78",
        frontcamera:"32MP",
        rearcamera:"50MP + 12MP + 12MP",
        ram:"8GB, 12GB",
        storage:"128GB, 256GB",
        battery:"4500mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:12,
        title:"OPPO Find X2",
        image:"/images/oppo/oppo.png" ,
        price:57990,
        stars:4.2,
        category:"Oppo",
        screen:"6.70",
        frontcamera:"32MP",
        rearcamera:"48MP + 13MP + 12MP",
        ram:"12GB",
        storage:"256GB",
        battery:"4200mAH",
        os:"Android 10",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:13, 
        title:"OPPO F19",
        image:"/images/oppo/oppo3.png" ,
        price:13990,
        stars:4.2,
        category:"Oppo",
        screen:"6.43",
        frontcamera:"16MP",
        rearcamera:"48MP + 2MP + 2MP",
        ram:"6GB",
        storage:"128GB",
        battery:"5000mAH",
        os:"Android 11",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:14,
        title:"OPPO F19 Pro+",
        image:"/images/oppo/oppo5.png" ,
        price:20989,
        stars:4.2,
        category:"Oppo",
        screen:"6.40",
        frontcamera:"16MP",
        rearcamera:"48MP + 8MP + 2MP + 2MP",
        ram:"8GB",
        storage:"128GB",
        battery:"4310mAH",
        os:"Android 11",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:15,
        title:"OPPO F21s Pro",
        image:"/images/oppo/oppo2.png" ,
        price:21989,
        stars:4.2,
        category:"Oppo",
        screen:"6.40",
        frontcamera:"16MP",
        rearcamera:"64MP + 2MP + 2MP",
        ram:"8GB",
        storage:"128GB",
        battery:"4500mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:16,
        title:"OPPO F21s 5G",
        image:"/images/oppo/oppo4.png" ,
        price:25990,
        stars:4.2,
        category:"Oppo",
        screen:"6.78",
        frontcamera:"16MP",
        rearcamera:"64MP + 2MP + 2MP",
        ram:"8GB",
        storage:"128GB",
        battery:"4500mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:17,
        title:"OPPO A16e",
        image:"/images/oppo/oppo6.png" ,
        price:9299,
        stars:4.2,
        category:"Oppo",
        screen:"6.52",
        frontcamera:"5MP",
        rearcamera:"13MP",
        ram:"3GB, 4GB",
        storage:"32GB, 64GB",
        battery:"4230mAH",
        os:"Android 11",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:18,
        title:"OPPO A76",
        image:"/images/oppo/oppo7.png" ,
        price:16490,
        stars:4.2,
        category:"Oppo",
        screen:"6.56",
        frontcamera:"8MP",
        rearcamera:"13MP + 2MP",
        ram:"4GB, 4GB",
        storage:"128GB",
        battery:"5000mAH",
        os:"Android 11",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:19,
        title:"OPPO A17k",
        image:"/images/oppo/oppo8.png" ,
        price:10499,
        stars:4.2,
        category:"Oppo",
        screen:"6.56",
        frontcamera:"5MP",
        rearcamera:"8MP",
        ram:"3GB",
        storage:"64GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:20,
        title:"OPPO A57",
        image:"/images/oppo/oppo9.png" ,
        price:12889,
        stars:4.2,
        category:"Oppo",
        screen:"6.56",
        frontcamera:"8MP",
        rearcamera:"13MP + 2MP",
        ram:"3GB",
        storage:"64GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:21,
        title:"OPPO A96",
        image:"/images/oppo/oppo10.png" ,
        price:19999,
        stars:4.2,
        category:"Oppo",
        screen:"6.59",
        frontcamera:"16MP",
        rearcamera:"50MP + 2MP",
        ram:"8GB",
        storage:"128GB, 256GB",
        battery:"5000mAH",
        os:"Android 11",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:22,
        title:"Samsung Galaxy A04e",
        image:"/images/samsung/samsung.webp" ,
        price:9299,
        stars:4.2,
        category:"Samsung",
        screen:"6.5",
        frontcamera:"5MP",
        rearcamera:"13MP + 2MP",
        ram:"3GB, 4GB",
        storage:"32GB, 64GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:23,
        title:"Samsung Galaxy M13",
        image:"/images/samsung/samsung2.webp" ,
        price:11999,
        stars:4.2,
        category:"Samsung",
        screen:"6.6",
        frontcamera:"8MP",
        rearcamera:"50MP + 2MP + 2MP",
        ram:"4GB, 6GB",
        storage:"64GB, 128GB",
        battery:"6000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:24,
        title:"Samsung Galaxy M04",
        image:"/images/samsung/samsung3.webp" ,
        price:9499,
        stars:4.2,
        category:"Samsung",
        screen:"6.5",
        frontcamera:"5MP",
        rearcamera:"13MP + 2MP",
        ram:"4GB, 8GB",
        storage:"64GB, 128GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:25,
        title:"Samsung Galaxy M33 5G",
        image:"/images/samsung/samsung4.webp" ,
        price:16780,
        stars:4.2,
        category:"Samsung",
        screen:"6.60",
        frontcamera:"8MP",
        rearcamera:"50MP + 5MP + 2MP + 2MP",
        ram:"8GB",
        storage:"128GB",
        battery:"6000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:26,
        title:"Samsung Galaxy M53 5G",
        image:"/images/samsung/samsung6.webp" ,
        price:23999,
        stars:4.2,
        category:"Samsung",
        screen:"6.70",
        frontcamera:"32MP",
        rearcamera:"108MP + 8MP + 2MP + 2MP",
        ram:"6GB, 8GB",
        storage:"128GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:27,
        title:"Samsung Galaxy A23",
        image:"/images/samsung/samsung7.webp" ,
        price:18499,
        stars:4.2,
        category:"Samsung",
        screen:"6.5",
        frontcamera:"8MP",
        rearcamera:"50MP + 5MP +2MP",
        ram:"4GB, 6GB, 8GB",
        storage:"64GB, 128GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:28,
        title:"Samsung Galaxy A13",
        image:"/images/samsung/samsung8.webp" ,
        price:12300,
        stars:4.2,
        category:"Samsung",
        screen:"6.60",
        frontcamera:"8MP",
        rearcamera:"50MP + 5MP + 2MP",
        ram:"4GB, GB",
        storage:"64GB, 128GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:29,
        title:"Samsung Galaxy A53 5G",
        image:"/images/samsung/samsung9.webp" ,
        price:31999,
        stars:4.2,
        category:"Samsung",
        screen:"6.50",
        frontcamera:"32MP",
        rearcamera:"64MP + 12MP + 5MP + 5MP",
        ram:"6GB, 8GB",
        storage:"128GB, 256GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:30,
        title:"Samsung Galaxy A73 5G",
        image:"/images/samsung/samsung10.webp" ,
        price:41999,
        stars:4.2,
        category:"Samsung",
        screen:"6.5",
        frontcamera:"32MP",
        rearcamera:"108MP",
        ram:"8GB",
        storage:"128GB, 256GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:31,
        title:"Samsung Galaxy S22",
        image:"/images/samsung/samsung11.webp" ,
        price:57199,
        stars:4.2,
        category:"Samsung",
        screen:"6.10",
        frontcamera:"10MP",
        rearcamera:"50MP + 10MP + 10MP",
        ram:"8GB",
        storage:"128GB, 256GB",
        battery:"3700mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:32,
        title:"Samsung Galaxy S20 FE 5G",
        image:"/images/samsung/samsung12.webp" ,
        price:33980,
        stars:4.2,
        category:"Samsung",
        screen:"6.5",
        frontcamera:"32MP",
        rearcamera:"12MP + 12MP + 8MP",
        ram:"6GB, 8GB",
        storage:"128GB, 256GB",
        battery:"4500mAH",
        os:"Android 10",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:33,
        title:"Samsung Galaxy Z Fold3 5G",
        image:"/images/samsung/samsung13.webp" ,
        price:94900,
        stars:4.2,
        category:"Samsung",
        screen:"7.60",
        frontcamera:"10MP + 4MP",
        rearcamera:"12MP + 12MP + 12MP",
        ram:"12Gb",
        storage:"256GB, 512GB",
        battery:"4400mAH",
        os:"Android 11",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:34,
        title:"Motorola moto g52",
        image:"/images/motorola/motorola.png" ,
        price:11999,
        stars:4.2,
        category:"Motorola",
        screen:"6.60",
        frontcamera:"16MP",
        rearcamera:"50MP + 8MP + 2MP",
        ram:"4GB, 6GB",
        storage:"64GB, 128GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:35,
        title:"Motorola moto g82 5g",
        image:"/images/motorola/motorola2.png" ,
        price:19999,
        stars:4.2,
        category:"Motorola",
        screen:"6.5",
        frontcamera:"16MP",
        rearcamera:"50MP + 8MP + 2MP",
        ram:"6GB, 8GB",
        storage:"128GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:36,
        title:"Motorola moto g62 5g",
        image:"/images/motorola/motorola3.png" ,
        price:15999,
        stars:4.2,
        category:"Motorola",
        screen:"6.5",
        frontcamera:"16MP",
        rearcamera:"50MP + 8MP + 2MP",
        ram:"6GB, 8GB",
        storage:"128GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:37,
        title:"Motorola moto g71 5g",
        image:"/images/motorola/motorola4.png" ,
        price:16999,
        stars:4.2,
        category:"Motorola",
        screen:"6.4",
        frontcamera:"16MP",
        rearcamera:"50MP + 8MP + 2MP",
        ram:"4GB, 6GB",
        storage:"128GB",
        battery:"5000mAH",
        os:"Android 11",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:38,
        title:"Motorola moto e22s",
        image:"/images/motorola/motorola5.png" ,
        price:8999,
        stars:4.2,
        category:"Motorola",
        screen:"6.5",
        frontcamera:"8MP",
        rearcamera:"16MP + 2MP",
        ram:"4GB",
        storage:"64GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:39,
        title:"Motorola moto e32",
        image:"/images/motorola/motorola 6.png" ,
        price:9499,
        stars:4.2,
        category:"Motorola",
        screen:"6.5",
        frontcamera:"8MP",
        rearcamera:"50MP + 2MP",
        ram:"4GB",
        storage:"64GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:40,
        title:"Motorola moto e40",
        image:"/images/motorola/motorla7.png" ,
        price:"7,999",
        stars:4.2,
        category:"Motorola",
        screen:"6.5",
        frontcamera:"5MP",
        rearcamera:"13MP + 2MP",
        ram:"3GB, 4GB",
        storage:"32GB, 64GB",
        battery:"5000mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:41,
        title:"Motorola edge20",
        image:"/images/motorola/motorola8.png" ,
        price:27800,
        stars:4.2,
        category:"Motorola",
        screen:"6.7",
        frontcamera:"32MP",
        rearcamera:"108MP + 16MP + 8MP",
        ram:"8GB",
        storage:"128GB",
        battery:"4000mAH",
        os:"Android 11",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:42,
        title:"Motorola edge30",
        image:"/images/motorola/motorola9.png" ,
        price:22999,
        stars:4.2,
        category:"Motorola",
        screen:"6.5",
        frontcamera:"32MP",
        rearcamera:"50MP + 50MP + 2MP",
        ram:"6GB, 8GB",
        storage:"128GB, 256GB",
        battery:"4020mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:43,
        title:"Motorola edge30 ultra",
        image:"/images/motorola/motorola10.png" ,
        price:54999,
        stars:4.2,
        category:"Motorola",
        screen:"6.67",
        frontcamera:"60MP",
        rearcamera:"200MP + 50MP + 12MP",
        ram:"12GB",
        storage:"256GB",
        battery:"4610mAH",
        os:"Android 12",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:44,
        title:"Motorola edge20 pro",
        image:"/images/motorola/motorola11.png" ,
        price:24999,
        stars:4.2,
        category:"Motorola",
        screen:"6.7",
        frontcamera:"32MP",
        rearcamera:"108MP + 16MP + 8MP",
        ram:"8GB, 12GB",
        storage:"128GB, 256GB",
        battery:"4500mAH",
        os:"Android 11",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:45,
        title:"iphone 13",
        image:"/images/apple/iphone.png" ,
        price:52654,
        stars:4.2,
        category:"Apple",
        screen:"6.10",
        frontcamera:"12MP",
        rearcamera:"12MP + 12MP",
        ram:"4GB",
        storage:"128GB, 256GB, 512GB",
        battery:"3240mAH",
        os:"iOS 15",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:46,
        title:"iphone 13mini",
        image:"/images/apple/iphone2.png" ,
        price:64900,
        stars:4.2,
        category:"Apple",
        screen:"5.4",
        frontcamera:"12MP",
        rearcamera:"12MP + 12MP",
        ram:"4GB",
        storage:"32GB, 64GB",
        battery:"2438mAH",
        os:"iOS 15",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:47,
        title:"iphone 14",
        image:"/images/apple/iphone3.png" ,
        price:73990,
        stars:4.2,
        category:"Apple",
        screen:"6.1",
        frontcamera:"12MP",
        rearcamera:"12MP + 12MP",
        ram:"6GB",
        storage:"128GB, 256GB, 512GB",
        battery:"3279mAH",
        os:"iOS 16",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:48,
        title:"iphone 14 Pro",
        image:"/images/apple/iphone4.png" ,
        price:139900,
        stars:4.2,
        category:"Apple",
        screen:"6.1",
        frontcamera:"12MP",
        rearcamera:"48MP + 12MP + 12MP",
        ram:"6GB",
        storage:"32GB, 64GB",
        battery:"3200mAH",
        os:"iOS 16",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:49,
        title:"iphone 12",
        image:"/images/apple/iphone5.png" ,
        price:54499,
        stars:4.2,
        category:"Apple",
        screen:"6.1",
        frontcamera:"12MP",
        rearcamera:"12MP + 12MP",
        ram:"4GB",
        storage:"64GB, 128GB, 256GB",
        battery:"2815mAH",
        os:"iOS 14.1",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:50,
        title:"iphone SE",
        image:"/images/apple/iphone6.png" ,
        price:26245,
        stars:4.2,
        category:"Apple",
        screen:"4.7",
        frontcamera:"7MP",
        rearcamera:"12MP",
        ram:"4GB",
        storage:"64GB, 128GB, 256GB",
        battery:"2018mAH",
        os:"iOS 15.4",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    {
        id:51,
        title:"iphone 14 Plus",
        image:"/images/apple/iphone7.png" ,
        price:59999,
        stars:4.2,
        category:"Apple",
        screen:"6.7",
        frontcamera:"12MP",
        rearcamera:"12MP + 12MP",
        ram:"6GB",
        storage:"128GB, 256GB, 512GB",
        battery:"4323mAH",
        os:"iOS 16",
        colors:["Red","Blue","Black","beige","green"],
        quantity:["1","2","3","4","5"]
    },
    
]

export default DATA;